services:
  fastapi-example:
    image: fastapi-example:latest
    container_name: fastapi-example
    ports:
      - 8000:8000
        #     environment:
        #       - DB_USER=""
        #       - DB_PASSWORD=""
        #       - DB_HOST=""
        #       - DB_PORT=""
        #       - DATABASE=""
        #       - API_KEY=""
    entrypoint: "uvicorn app.main:app --host 0.0.0.0 --port 8000"

